default_meta: []
default_status: proposed
directory: docs/explain/architecture-decisions
id_digit_number: 4
supported_statuses:
- proposed
- accepted
- rejected
- superseded
- amended
- deprecated
template_file: docs/explain/architecture-decisions/adr_template.md
