[book]
language = "en"
multilingual = false
src = "."
title = "The Standard Documentation"

[build]
build-dir = "book"

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/mermaid.min.js", "theme/mermaid-init.js", "theme/pagetoc.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
