[book]
language = "en"
multilingual = false
src = "."
title = "The Standard Documentation"

[build]
build-dir = "docs/book"

[output.html]
additional-js = ["static/mermaid.min.js", "static/mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
